import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Box, Container, Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="lg">
        <Box
          sx={{
            my: 4,
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Typography
            variant="h4"
            component="h1"
            gutterBottom
            color="secondary"
          >
            Material UI - Next.js example in TypeScript
          </Typography>
          <Typography variant="h4" color="error">
            Test colors
          </Typography>

          <Link href="/about">Go to the about page</Link>
          <Image
            src="/vercel.svg"
            alt="Vercel Logo"
            width={100}
            height={24}
            priority
          />
        </Box>
      </Container>
    </>
  );
}
